name: deploy
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - run: pip install mkdocs-material 
      - run: mkdocs build
      - run: aws s3 sync site/ s3://${{ vars.S3_BUCKET }} --delete --cache-control max-age=31536000,public
      # - run: aws s3 cp s3://${{ vars.S3_BUCKET }}/index.html s3://${{ vars.S3_BUCKET }}/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read
      - run: aws cloudfront create-invalidation --distribution-id ${{ vars.CF_ID }} --paths "/*"